# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3b7e3aacf9ffd336610ba9bbf4a4018efeddd96b784a947c3c21cb73d10ed158c1aee28d63393f35f6e6d9fd64d73bc58a96d83db673aa12405611a7b23d8556

test:
  secret_key_base: 07b7dd1356b1f5d768483b812c3d6d70d342a804f52e6d8094ac7ad321e0ad915580e3116bef96122980ee2387461ea671dbf686707a8c90aa6607ec3b185ed8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
